services:
  webapp:
    build: ./webapp
    links:
      - db
    ports:
      - "80:80"
      - "443:443"
    restart: always
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro