services:
  webapp:
    build: ./webapp
    links:
      - db
    ports:
      - "5000:80"
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro